server:
  port: 8083

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

rabbitmq:
  exchange:
    name: urgencias
  queue:
    name:
      supervisor: q.pacientes.supervisor
  routing:
    key:
      supervisor: pacientes.*
