# Puerto del servidor
server.port=8080

# Configuración de conexión a RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Nombre del exchange de tipo Topic
rabbitmq.exchange.name=urgencias

# Nombres de las colas
rabbitmq.queue.name.leve=q.pacientes.leve
rabbitmq.queue.name.grave=q.pacientes.grave
rabbitmq.queue.name.critico=q.pacientes.critico
rabbitmq.queue.name.supervisor=q.pacientes.supervisor

# Routing keys para cada grado de paciente
rabbitmq.routing.key.leve=pacientes.leve
rabbitmq.routing.key.grave=pacientes.grave
rabbitmq.routing.key.critico=pacientes.critico
rabbitmq.routing.key.supervisor=pacientes.*