# Configuración base del Gateway.
# Importa su configuración real desde el Config Server en perfil local.
# Autores: Victor Sanz, Carlos Marques, Sara Cardenas

spring:
  application:
    name: gateway
  config:
    import: optional:configserver:http://localhost:8888
  profiles:
    active: local
