server:
  port: 8081

spring:
  main:
    web-application-type: reactive
  r2dbc:
    url: r2dbc:h2:mem:///triajedb;DB_CLOSE_DELAY=-1
    username: sa
    password:
  h2:
    console:
      enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

rabbitmq:
  exchange:
    name: urgencias
  queue:
    name:
      leve: q.pacientes.leve
      grave: q.pacientes.grave
      critico: q.pacientes.critico
      supervisor: q.pacientes.supervisor
  routing:
    key:
      leve: pacientes.leve
      grave: pacientes.grave
      critico: pacientes.critico
      supervisor: pacientes.*
