# Configuración base de API1 (Triaje y Camas).
# Importa configuración extendida desde el Config Server en perfil local.
# Autores: Victor Sanz, Carlos Marques, Sara Cardenas

spring:
  application:
    name: api1-triaje-camas
  config:
    import: optional:configserver:http://localhost:8888
  profiles:
    active: local
