# Configuración base de API3 (Supervisor Médico).
# Importa configuración extendida desde el Config Server en perfil local.
# Autores: Victor Sanz, Carlos Marques, Sara Cardenas

spring:
  application:
    name: api3-supervisor-medico
  config:
    import: optional:configserver:http://localhost:8888
  profiles:
    active: local
